apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: cfg-up-azuretest
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/garreeoke/cfg-up-azuretest
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This starter configuration for azure
    meta.crossplane.io/readme: |
      This starter configuration for azure
spec:
  crossplane:
    version: ">=v1.11.0-0"
    dependsOn:
      - provider: xpkg.upbound.io/upbound/provider-azure
        version: ">=v0.30.0"
      - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
        version: ">=v0.7.0"
