apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: x-vm-redis.azuretest.upbound.io
  labels:
    azuretest.upbound.io/option: vm-redis
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: azuretest.upbound.io/v1alpha1
    kind: XVmDbCombo
  patchSets:
    - name: common
      patches:
        - fromFieldPath: spec.location
          toFieldPath: spec.location
        - fromFieldPath: spec.resourceGroup
          toFieldPath: spec.resourceGroup
  resources:
    - name: virtualMachine
      base:
        apiVersion: azuretest.upbound.io/v1alpha1
        kind: XVirtualMachine
        metadata:
          namespace: default
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.id
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
    - name: redisDb
      base:
        apiVersion: azuretest.upbound.io/v1alpha1
        kind: XDataBase
        metadata:
          namespace: default
        spec:
          compositionSelector:
            matchLabels:
              azuretest.upbound.io/option: redis
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.id
          transforms:
            - type: string
              string:
                fmt: "%s-redis"
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-redis"



