apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvmdbcombos.azuretest.upbound.io
spec:
  group: azuretest.upbound.io
  names:
    kind: XVmDbCombo
    plural: xvmdbcombos
  claimNames:
    kind: VmDbCombo
    plural: vmdbcombos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: "Create database and vm resources for TechMahindra demo"
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: "base id prefix for all managed resources"
                location:
                  type: string
                  description: location
                resourceGroup:
                  type: string
                  description: azure resource group
              required:
                - id
                - location
                - resourceGroup